/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AoeDiscEffect: typeof import('./app/utils/effects/aoe-disc').AoeDiscEffect
  const AoeGroupEffect: typeof import('./app/utils/effects/aoe-group').AoeGroupEffect
  const AoeRingEffect: typeof import('./app/utils/effects/aoe-ring').AoeRingEffect
  const AoeSquareEffect: typeof import('./app/utils/effects/aoe-square').AoeSquareEffect
  const AoeSquareGridEffect: typeof import('./app/utils/effects/aoe-square-grid').AoeSquareGridEffect
  const Arena: typeof import('./app/utils/arenas/arena').Arena
  const Bab: typeof import('@babylonjs/core')
  const Boss: typeof import('./app/utils/boss').Boss
  const CastBarEffect: typeof import('./app/utils/effects/cast-bar').CastBarEffect
  const Character: typeof import('./app/utils/character').Character
  const Clock: typeof import('./app/utils/clock').Clock
  const ClockSpotsTutorial: typeof import('./app/utils/fights/tutorial-clock-spots').ClockSpotsTutorial
  const Color3: typeof import('@babylonjs/core').Color3
  const Debug: typeof import('debug').default
  const DefaultBossOptions: typeof import('./app/utils/boss').DefaultBossOptions
  const DefaultCharacterOptions: typeof import('./app/utils/character').DefaultCharacterOptions
  const DefaultFightSchedulingMode: typeof import('./app/utils/fights/fight').DefaultFightSchedulingMode
  const DefaultFightSectionSchedulingMode: typeof import('./app/utils/sections/fight-section').DefaultFightSectionSchedulingMode
  const DefaultMechanicSchedulingMode: typeof import('./app/utils/mechanics/mechanic').DefaultMechanicSchedulingMode
  const DiceEffect: typeof import('./app/utils/effects/dice').DiceEffect
  const DistributeEffect: typeof import('./app/utils/effects/distribute').DistributeEffect
  const E12SFight: typeof import('./app/utils/fights/e12s').E12SFight
  const E12SPrimalCombination: typeof import('./app/utils/mechanics/e12s-primal-combination').E12SPrimalCombination
  const Effect: typeof import('./app/utils/effects/effect').Effect
  const EffectScope: typeof import('vue').EffectScope
  const EffectStage: typeof import('./app/utils/effects/effect').EffectStage
  const EventEmitter: typeof import('tseep').EventEmitter
  const Fight: typeof import('./app/utils/fights/fight').Fight
  const FightCollection: typeof import('./app/utils/fight-collection').FightCollection
  const FightSection: typeof import('./app/utils/sections/fight-section').FightSection
  const FuseOrFoeSection: typeof import('./app/utils/sections/m3s-fuse-or-foe').FuseOrFoeSection
  const Indicator: typeof import('./app/utils/indicator').Indicator
  const KBTowerEffect: typeof import('./app/utils/effects/kb-tower').KBTowerEffect
  const M2SAlarmPheromones2: typeof import('./app/utils/mechanics/m2s-alarm-pheromones-2').M2SAlarmPheromones2
  const M2SAlarmPheromones2Effect: typeof import('./app/utils/effects/m2s-alarm-pheromones-2').M2SAlarmPheromones2Effect
  const M2SBeeSting: typeof import('./app/utils/mechanics/m2s-bee-sting').M2SBeeSting
  const M2SFight: typeof import('./app/utils/fights/m2s').M2SFight
  const M2SPoisonSting: typeof import('./app/utils/mechanics/m2s-poison-sting').M2SPoisonSting
  const M2SPoisonStingEffect: typeof import('./app/utils/effects/m2s-poison-sting').M2SPoisonStingEffect
  const M2SStageCombo: typeof import('./app/utils/mechanics/m2s-stage-combo').M2SStageCombo
  const M2STutorial: typeof import('./app/utils/fights/tutorial-m2s').M2STutorial
  const M2SXOfVenom: typeof import('./app/utils/mechanics/m2s-x-of-venom').M2SXOfVenom
  const M3SBarbarousBarrage: typeof import('./app/utils/mechanics/m3s-barbarous-barrage').M3SBarbarousBarrage
  const M3SFight: typeof import('./app/utils/fights/m3s').M3SFight
  const M3SInfernalSpin: typeof import('./app/utils/mechanics/m3s-infernal-spin').M3SInfernalSpin
  const M3SInfernalSpinEffect: typeof import('./app/utils/effects/m3s-infernal-spin').M3SInfernalSpinEffect
  const M3SLariat: typeof import('./app/utils/mechanics/m3s-lariat').M3SLariat
  const M4SFight: typeof import('./app/utils/fights/m4s').M4SFight
  const M4SNearFarIndicatorEffect: typeof import('./app/utils/effects/m4s-near-far-indicator').M4SNearFarIndicatorEffect
  const M4STutorialFight: typeof import('./app/utils/fights/tutorial-m4s-widening-narrowing-witch-hunt').M4STutorialFight
  const M4SWideningNarrowingWitchHunt: typeof import('./app/utils/mechanics/m4s-widening-narrowing-witch-hunt').M4SWideningNarrowingWitchHunt
  const M4SWitchHuntBaits: typeof import('./app/utils/mechanics/m4s-witch-hunt-baits').M4SWitchHuntBaits
  const Marker: typeof import('./app/utils/marker').Marker
  const MaxPlayerHeight: typeof import('./app/utils/character').MaxPlayerHeight
  const Mechanic: typeof import('./app/utils/mechanics/mechanic').Mechanic
  const MechanicStage: typeof import('./app/utils/mechanics/mechanic').MechanicStage
  const MinPlayerHeight: typeof import('./app/utils/character').MinPlayerHeight
  const P9SSection: typeof import('./app/utils/sections/p9s-levinstrike').P9SSection
  const PipPositions: typeof import('./app/utils/effects/dice').PipPositions
  const PreyMarkerEffect: typeof import('./app/utils/effects/prey-marker').PreyMarkerEffect
  const StageCastEffect: typeof import('./app/utils/effects/stage-cast').StageCastEffect
  const StageComboCastEffect: typeof import('./app/utils/effects/stage-combo-cast').StageComboCastEffect
  const Steering: typeof import('./app/utils/steering').Steering
  const TetherEffect: typeof import('./app/utils/effects/tether').TetherEffect
  const Vector2: typeof import('@babylonjs/core').Vector2
  const Vector3: typeof import('@babylonjs/core').Vector3
  const Vector4: typeof import('@babylonjs/core').Vector4
  const Waymark: typeof import('./app/utils/waymark').Waymark
  const WideningNarrowingWitchHuntSection: typeof import('./app/utils/sections/m4s-widening-narrowing-witch-hunt').WideningNarrowingWitchHuntSection
  const addStacks: typeof import('./app/utils/status').addStacks
  const addStatus: typeof import('./app/utils/status').addStatus
  const addTag: typeof import('./app/utils/meta-helpers').addTag
  const arenaBounds: typeof import('./app/materials/arenaBounds').default
  const arenaBoundsMaterial: typeof import('./app/materials/arenaBounds').arenaBoundsMaterial
  const arenaGridMat: typeof import('./app/utils/arenas/mats').arenaGridMat
  const arenaMats: typeof import('./app/utils/arenas/mats').arenaMats
  const arenas: typeof import('./app/utils/arenas/index').default
  const arenasCollection: typeof import('./app/utils/arenas/index').arenasCollection
  const b: typeof import('from').b
  const clearStacks: typeof import('./app/utils/status').clearStacks
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPixelateShader: typeof import('./app/materials/pixelate').createPixelateShader
  const createRingMesh: typeof import('./app/utils/ring').createRingMesh
  const customRef: typeof import('vue').customRef
  const d: typeof import('from').d
  const decodeEffect: typeof import('./app/utils/decode-fight').decodeEffect
  const decodeFight: typeof import('./app/utils/decode-fight').decodeFight
  const decodeFightSection: typeof import('./app/utils/decode-fight').decodeFightSection
  const decodeMechanic: typeof import('./app/utils/decode-fight').decodeMechanic
  const decodeScheduled: typeof import('./app/utils/decode-fight').decodeScheduled
  const decodeScheduledEffect: typeof import('./app/utils/decode-fight').decodeScheduledEffect
  const decodeScheduledFightSection: typeof import('./app/utils/decode-fight').decodeScheduledFightSection
  const decodeScheduledMechanic: typeof import('./app/utils/decode-fight').decodeScheduledMechanic
  const default: typeof import('debug').default
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const degToRads: typeof import('./app/utils/vector-helpers').degToRads
  const e: typeof import('from').e
  const e12sArenaMat: typeof import('./app/utils/arenas/mats').e12sArenaMat
  const effectScope: typeof import('vue').effectScope
  const effects: typeof import('./app/utils/effects/index').default
  const effectsCollection: typeof import('./app/utils/effects/index').effectsCollection
  const enemyMarker: typeof import('./app/materials/enemy-marker').default
  const enemyMarkerMaterial: typeof import('./app/materials/enemy-marker').enemyMarkerMaterial
  const executeScheduled: typeof import('./app/utils/scheduled').executeScheduled
  const fights: typeof import('./app/utils/fights/index').default
  const fightsCollection: typeof import('./app/utils/fights/index').fightsCollection
  const frag: typeof import('./app/materials/pixelate').frag
  const g: typeof import('from').g
  const getArenaPosition: typeof import('./app/utils/positioning').getArenaPosition
  const getBasicValues: typeof import('./app/utils/decode-fight').getBasicValues
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getInterpolatedPosition: typeof import('./app/utils/positioning').getInterpolatedPosition
  const getOtherRoles: typeof import('./app/utils/roles').getOtherRoles
  const getPosition: typeof import('./app/utils/positioning').getPosition
  const getPositionVector: typeof import('./app/utils/positioning').getPositionVector
  const getRoleType: typeof import('./app/utils/roles').getRoleType
  const getScheduledDuration: typeof import('./app/utils/scheduled').getScheduledDuration
  const getScheduledJSONSnapshot: typeof import('./app/utils/scheduled').getScheduledJSONSnapshot
  const getStatus: typeof import('./app/utils/status').getStatus
  const getStatusSeconds: typeof import('./app/utils/status').getStatusSeconds
  const getVectorThetaLength: typeof import('./app/utils/vector-helpers').getVectorThetaLength
  const h: typeof import('vue').h
  const hasTags: typeof import('./app/utils/meta-helpers').hasTags
  const imageArenaMat: typeof import('./app/utils/arenas/mats').imageArenaMat
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isScheduled: typeof import('./app/utils/scheduled').isScheduled
  const isShallow: typeof import('vue').isShallow
  const isSupportRole: typeof import('./app/utils/roles').isSupportRole
  const isWithinRadius: typeof import('./app/utils/vector-helpers').isWithinRadius
  const loadScheduledJSONSnapshot: typeof import('./app/utils/scheduled').loadScheduledJSONSnapshot
  const m2sArenaMat: typeof import('./app/utils/arenas/mats').m2sArenaMat
  const m2sStage2ArenaMat: typeof import('./app/utils/arenas/mats').m2sStage2ArenaMat
  const m3sArenaMat: typeof import('./app/utils/arenas/mats').m3sArenaMat
  const m4sArenaMat: typeof import('./app/utils/arenas/mats').m4sArenaMat
  const makeStatus: typeof import('./app/utils/status').makeStatus
  const mapMaterialP9S: typeof import('./app/materials/p9s').mapMaterialP9S
  const markRaw: typeof import('vue').markRaw
  const marker: typeof import('./app/materials/marker').default
  const markerMaterial: typeof import('./app/materials/marker').markerMaterial
  const mats: typeof import('./app/utils/arenas/mats').default
  const mechanics: typeof import('./app/utils/mechanics/index').default
  const mechanicsCollection: typeof import('./app/utils/mechanics/index').mechanicsCollection
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const p9s: typeof import('./app/materials/p9s').default
  const p9sArenaMat: typeof import('./app/utils/arenas/mats').p9sArenaMat
  const parseNumber: typeof import('./app/utils/parse-number').parseNumber
  const pixelate: typeof import('./app/materials/pixelate').default
  const polarArenaMat: typeof import('./app/utils/arenas/mats').polarArenaMat
  const polarGrid: typeof import('./app/materials/polarGrid').default
  const polarGridMaterial: typeof import('./app/materials/polarGrid').polarGridMaterial
  const provide: typeof import('vue').provide
  const radToDegs: typeof import('./app/utils/vector-helpers').radToDegs
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const removeStacks: typeof import('./app/utils/status').removeStacks
  const removeStatus: typeof import('./app/utils/status').removeStatus
  const removeTag: typeof import('./app/utils/meta-helpers').removeTag
  const resolveComponent: typeof import('vue').resolveComponent
  const ring: typeof import('./app/utils/ring').default
  const roundAoe: typeof import('./app/materials/roundAoe').default
  const roundAoeMaterial: typeof import('./app/materials/roundAoe').roundAoeMaterial
  const roundWaymarkMaterial: typeof import('./app/materials/waymarkRound').roundWaymarkMaterial
  const sections: typeof import('./app/utils/sections/index').default
  const sectionsCollection: typeof import('./app/utils/sections/index').sectionsCollection
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const squareAoe: typeof import('./app/materials/squareAoe').default
  const squareAoeMaterial: typeof import('./app/materials/squareAoe').squareAoeMaterial
  const squareWaymarkMaterial: typeof import('./app/materials/waymarkSquare').squareWaymarkMaterial
  const standardAoe: typeof import('./app/materials/standardAoe').default
  const standardAoeMaterial: typeof import('./app/materials/standardAoe').standardAoeMaterial
  const standardPartyRoles: typeof import('./app/utils/roles').standardPartyRoles
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const traverseScheduled: typeof import('./app/utils/scheduled').traverseScheduled
  const triggerRef: typeof import('vue').triggerRef
  const u: typeof import('from').u
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const vectorAngle: typeof import('./app/utils/vector-helpers').vectorAngle
  const vert: typeof import('./app/materials/pixelate').vert
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const waymarkRound: typeof import('./app/materials/waymarkRound').default
  const waymarkSquare: typeof import('./app/materials/waymarkSquare').default
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Arena, ArenaShape, ArenaOptions, Arena } from './app/utils/arenas/arena'
  import('./app/utils/arenas/arena')
  // @ts-ignore
  export type { Boss, BossOptions } from './app/utils/boss'
  import('./app/utils/boss')
  // @ts-ignore
  export type { Character, CharacterOptions } from './app/utils/character'
  import('./app/utils/character')
  // @ts-ignore
  export type { Clock } from './app/utils/clock'
  import('./app/utils/clock')
  // @ts-ignore
  export type { FightDecodeOptions } from './app/utils/decode-fight'
  import('./app/utils/decode-fight')
  // @ts-ignore
  export type { AoeDiscEffect, AoeDiscEffectOptions } from './app/utils/effects/aoe-disc'
  import('./app/utils/effects/aoe-disc')
  // @ts-ignore
  export type { AoeGroupEffect, AoeGroupEffectOptions } from './app/utils/effects/aoe-group'
  import('./app/utils/effects/aoe-group')
  // @ts-ignore
  export type { AoeRingEffect, AoeRingEffectOptions } from './app/utils/effects/aoe-ring'
  import('./app/utils/effects/aoe-ring')
  // @ts-ignore
  export type { AoeSquareGridEffect, GridOrientation, GridPattern, AoeSquareGridEffectOptions } from './app/utils/effects/aoe-square-grid'
  import('./app/utils/effects/aoe-square-grid')
  // @ts-ignore
  export type { AoeSquareEffect, AoeSquareEffectOptions } from './app/utils/effects/aoe-square'
  import('./app/utils/effects/aoe-square')
  // @ts-ignore
  export type { CastBarEffect, CastBarEffectOptions } from './app/utils/effects/cast-bar'
  import('./app/utils/effects/cast-bar')
  // @ts-ignore
  export type { DiceEffect, DiceEffectOptions } from './app/utils/effects/dice'
  import('./app/utils/effects/dice')
  // @ts-ignore
  export type { DistributeEffect, DistributionType, DistributionItem, DistributeEffectOptions } from './app/utils/effects/distribute'
  import('./app/utils/effects/distribute')
  // @ts-ignore
  export type { Effect, EffectTargetType, EffectTarget, EffectPositionType, EffectOptions, Effect } from './app/utils/effects/effect'
  import('./app/utils/effects/effect')
  // @ts-ignore
  export type { KBTowerEffect, KBTowerEffectOptions } from './app/utils/effects/kb-tower'
  import('./app/utils/effects/kb-tower')
  // @ts-ignore
  export type { M2SAlarmPheromones2Effect } from './app/utils/effects/m2s-alarm-pheromones-2'
  import('./app/utils/effects/m2s-alarm-pheromones-2')
  // @ts-ignore
  export type { M2SPoisonStingEffect } from './app/utils/effects/m2s-poison-sting'
  import('./app/utils/effects/m2s-poison-sting')
  // @ts-ignore
  export type { M3SInfernalSpinEffect } from './app/utils/effects/m3s-infernal-spin'
  import('./app/utils/effects/m3s-infernal-spin')
  // @ts-ignore
  export type { M4SNearFarIndicatorEffect, M4SNearFarIndicatorEffectOptions } from './app/utils/effects/m4s-near-far-indicator'
  import('./app/utils/effects/m4s-near-far-indicator')
  // @ts-ignore
  export type { PreyMarkerEffect, PreyMarkerEffectOptions } from './app/utils/effects/prey-marker'
  import('./app/utils/effects/prey-marker')
  // @ts-ignore
  export type { StageCastEffect, StageCastEffectOptions } from './app/utils/effects/stage-cast'
  import('./app/utils/effects/stage-cast')
  // @ts-ignore
  export type { StageComboCastEffect, StageComboCastEffectOptions } from './app/utils/effects/stage-combo-cast'
  import('./app/utils/effects/stage-combo-cast')
  // @ts-ignore
  export type { TetherEffect, TetherEffectOptions } from './app/utils/effects/tether'
  import('./app/utils/effects/tether')
  // @ts-ignore
  export type { FightCollection, CharacterName, FightCollectionOptions } from './app/utils/fight-collection'
  import('./app/utils/fight-collection')
  // @ts-ignore
  export type { E12SFight, E12SFightOptions } from './app/utils/fights/e12s'
  import('./app/utils/fights/e12s')
  // @ts-ignore
  export type { Fight, FightOptions, Fight } from './app/utils/fights/fight'
  import('./app/utils/fights/fight')
  // @ts-ignore
  export type { M2SFight, M2SFightOptions } from './app/utils/fights/m2s'
  import('./app/utils/fights/m2s')
  // @ts-ignore
  export type { M3SFight, M3SFightOptions } from './app/utils/fights/m3s'
  import('./app/utils/fights/m3s')
  // @ts-ignore
  export type { M4SFight, M4SFightOptions } from './app/utils/fights/m4s'
  import('./app/utils/fights/m4s')
  // @ts-ignore
  export type { ClockSpotsTutorial, ClockSpotsTutorialOptions } from './app/utils/fights/tutorial-clock-spots'
  import('./app/utils/fights/tutorial-clock-spots')
  // @ts-ignore
  export type { M2STutorial, M2STutorialOptions } from './app/utils/fights/tutorial-m2s'
  import('./app/utils/fights/tutorial-m2s')
  // @ts-ignore
  export type { M4STutorialFight, M4STutorialFightOptions } from './app/utils/fights/tutorial-m4s-widening-narrowing-witch-hunt'
  import('./app/utils/fights/tutorial-m4s-widening-narrowing-witch-hunt')
  // @ts-ignore
  export type { Indicator, IndicatorOptions } from './app/utils/indicator'
  import('./app/utils/indicator')
  // @ts-ignore
  export type { Marker, MarkerOptions } from './app/utils/marker'
  import('./app/utils/marker')
  // @ts-ignore
  export type { E12SPrimalCombination, E12SPrimalCombinationOptions } from './app/utils/mechanics/e12s-primal-combination'
  import('./app/utils/mechanics/e12s-primal-combination')
  // @ts-ignore
  export type { Mechanic, MechanicOptions, Mechanic } from './app/utils/mechanics/mechanic'
  import('./app/utils/mechanics/mechanic')
  // @ts-ignore
  export type { M2SAlarmPheromones2, M2SAlarmPheromones2Options } from './app/utils/mechanics/m2s-alarm-pheromones-2'
  import('./app/utils/mechanics/m2s-alarm-pheromones-2')
  // @ts-ignore
  export type { M2SBeeSting, M2SBeeStingOptions } from './app/utils/mechanics/m2s-bee-sting'
  import('./app/utils/mechanics/m2s-bee-sting')
  // @ts-ignore
  export type { M2SPoisonSting, M2SPoisonStingOptions } from './app/utils/mechanics/m2s-poison-sting'
  import('./app/utils/mechanics/m2s-poison-sting')
  // @ts-ignore
  export type { M2SStageCombo, M2SStageComboOptions } from './app/utils/mechanics/m2s-stage-combo'
  import('./app/utils/mechanics/m2s-stage-combo')
  // @ts-ignore
  export type { M2SXOfVenom, M2SXOfVenomOptions } from './app/utils/mechanics/m2s-x-of-venom'
  import('./app/utils/mechanics/m2s-x-of-venom')
  // @ts-ignore
  export type { M3SBarbarousBarrage, M3SBarbarousBarrageOptions } from './app/utils/mechanics/m3s-barbarous-barrage'
  import('./app/utils/mechanics/m3s-barbarous-barrage')
  // @ts-ignore
  export type { M3SInfernalSpin, M3SInfernalSpinOptions } from './app/utils/mechanics/m3s-infernal-spin'
  import('./app/utils/mechanics/m3s-infernal-spin')
  // @ts-ignore
  export type { M3SLariat, LariatType, LariatPosition, M3SLariatOptions } from './app/utils/mechanics/m3s-lariat'
  import('./app/utils/mechanics/m3s-lariat')
  // @ts-ignore
  export type { M4SWideningNarrowingWitchHunt, WitchHuntType, M4SWideningNarrowingWitchHuntOptions } from './app/utils/mechanics/m4s-widening-narrowing-witch-hunt'
  import('./app/utils/mechanics/m4s-widening-narrowing-witch-hunt')
  // @ts-ignore
  export type { M4SWitchHuntBaits, BaitType, BaitList, M4SWitchHuntBaitsOptions } from './app/utils/mechanics/m4s-witch-hunt-baits'
  import('./app/utils/mechanics/m4s-witch-hunt-baits')
  // @ts-ignore
  export type { Tags, Stacks } from './app/utils/meta-helpers'
  import('./app/utils/meta-helpers')
  // @ts-ignore
  export type { PositionType, PositionTarget, PositionOption } from './app/utils/positioning'
  import('./app/utils/positioning')
  // @ts-ignore
  export type { RingOptions } from './app/utils/ring'
  import('./app/utils/ring')
  // @ts-ignore
  export type { RoleType, Role } from './app/utils/roles'
  import('./app/utils/roles')
  // @ts-ignore
  export type { ScheduleMode, Scheduled, ScheduledParent } from './app/utils/scheduled'
  import('./app/utils/scheduled')
  // @ts-ignore
  export type { FightSection, SectionOptions, FightSection } from './app/utils/sections/fight-section'
  import('./app/utils/sections/fight-section')
  // @ts-ignore
  export type { FuseOrFoeSection, FuseOrFoeSectionOptions } from './app/utils/sections/m3s-fuse-or-foe'
  import('./app/utils/sections/m3s-fuse-or-foe')
  // @ts-ignore
  export type { WideningNarrowingWitchHuntSection, WideningNarrowingWitchHuntSectionOptions } from './app/utils/sections/m4s-widening-narrowing-witch-hunt'
  import('./app/utils/sections/m4s-widening-narrowing-witch-hunt')
  // @ts-ignore
  export type { P9SSection, P9SSectionOptions } from './app/utils/sections/p9s-levinstrike'
  import('./app/utils/sections/p9s-levinstrike')
  // @ts-ignore
  export type { Status, PartialStatus } from './app/utils/status'
  import('./app/utils/status')
  // @ts-ignore
  export type { Steering, Force, SteeringOptions } from './app/utils/steering'
  import('./app/utils/steering')
  // @ts-ignore
  export type { Waymark, WaymarkName, WaymarkOptions } from './app/utils/waymark'
  import('./app/utils/waymark')
}
